//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreManagementApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Model
    {
        public int Srno { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> BrandId { get; set; }
    }
}
