//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreManagementApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Storage
    {
        public int Srno { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> Recieved_Date { get; set; }
        public Nullable<System.DateTime> Sold_Date { get; set; }
        public Nullable<bool> Sold_Flag { get; set; }
        public Nullable<double> Discount_Percentage { get; set; }
        public Nullable<double> Discount_Price { get; set; }
        public Nullable<double> Sold_Price { get; set; }
        public string Customer { get; set; }
        public double Said_Price { get; set; }
    }
}
