//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreManagementApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileStoreManagementEntities : DbContext
    {
        public MobileStoreManagementEntities()
            : base("name=MobileStoreManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Master_Brand> Master_Brand { get; set; }
        public virtual DbSet<Master_Model> Master_Model { get; set; }
        public virtual DbSet<Master_Storage> Master_Storage { get; set; }
    }
}
